FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY docker_images/event_listener/requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --upgrade pytube

COPY src/event_listener.py /app/

ENV PYTHONUNBUFFERED=1